### ISSUE TITLE
Onclick listener

### ISSUE THREAD

**Issue by ghost** [FoamyGuy/StackSites#1]
Instead of opening a new activity,your application opens a website to the specific url.Please add open activity from intent..so that then the list content displays in a new activity within the app

**Comment by FoamyGuy** [comment]
I put out the source code for this application for free as a learning tool. You may feel free to modify it to suite your needs, but I am not going to make the changes for you.

**Comment by ghost** [comment]
i just needed guidance on the onlicklistener,i have no idea how to implement it,i understand your approach and its very muh appreciated,but you as an expert,please guide me on how to add the onlick listener to open a new ativity and display the list items as full content..your assistancce will be very much apppreciated.

**Comment by ghost** [comment]
ok,thanks...i figured it out
